Fix undefined reference to yylex: Only link FLEX_LIBRARIES on Apple
On Arch, building STLRom fails with "undefined reference to `yylex'".
Declaring a C yylex function does not fix the issue.
According to
https://github.com/Seifert69/DikuMUD3/issues/70#issuecomment-1100932157,
a possible cause is linking FLEX_LIBRARIES, which was added to
CMakeLists.txt as a fix for MacOS in 246fd9d. This commit fixes the
issue by only linking FLEX_LIBRARIES when they are defined AND when
building on MacOS.